### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by sebastianmacias** [Vivify-Ideas/python-django-drf-boilerplate#13]
Hi,

I'm considering using this template to start a new project. Do you plan to add documentation on for instance how to create celery tasks, use beat, docker-compose-swarm and other included features?

Thanks!

**Comment by nikolasp** [comment]
Hey @sebastianmacias 

Sorry for not getting back to you sooner.
This isn't really in our scope, but we are opened to any PR if improves the boilerplate.

There are some useful articles you should definitely check out:
- https://www.caktusgroup.com/blog/2021/08/11/using-celery-scheduling-tasks/
- https://devopscon.io/blog/continuous-deployment-docker-swarm/

Thanks for understanding!

**Comment by sebastianmacias** [comment]
Thank you
